Write a NumPy program to sort an given array by the nth column.

In [1]:
# import library
import numpy as np

In [7]:
# create variable or array using random function in numpy
print("Original array:\n")
nums = np.random.randint(0,10,(3,3))
print(nums)

Original array:

[[9 9 1]
 [4 8 2]
 [0 1 8]]


In [8]:
# Sort the nth column in the array 
print("\nSort the said array by the nth column: ")
print(nums[nums[:,1].argsort()])


Sort the said array by the nth column: 
[[0 1 8]
 [4 8 2]
 [9 9 1]]


In [9]:
# can be used in one cell also if u get same output in different cells
print("Original array:\n")
nums = np.random.randint(0,10,(3,3))
print(nums)
print("\nSort the said array by the nth column: ")
print(nums[nums[:,1].argsort()])

Original array:

[[9 5 5]
 [3 1 2]
 [6 7 9]]

Sort the said array by the nth column: 
[[3 1 2]
 [9 5 5]
 [6 7 9]]
